server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**

        # Swagger UI routes per service
        - id: auth-service-docs
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/v3/api-docs/**
        - id: account-service-docs
          uri: lb://account-service
          predicates:
            - Path=/account-service/v3/api-docs/**
        - id: transaction-service-docs
          uri: lb://transaction-service
          predicates:
            - Path=/transaction-service/v3/api-docs/**
        - id: analytics-service-docs
          uri: lb://analytics-service
          predicates:
            - Path=/analytics-service/v3/api-docs/**
