server:
  port: 8082

spring:
  application:
    name: account-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/account_db
    username: ${DB_USER:ledgerlite}
    password: ${DB_PASSWORD:ledgerlite}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
