apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ledgerlite
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ledgerlite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      enableServiceLinks: false
      containers:
        - name: api-gateway
          image: ledgerlite/api-gateway:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: ZIPKIN_URL
              value: http://zipkin:9411
            - name: REDIS_HOST
              value: redis
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8081
            - name: ACCOUNT_SERVICE_URL
              value: http://account-service:8082
            - name: TRANSACTION_SERVICE_URL
              value: http://transaction-service:8083
            - name: ANALYTICS_SERVICE_URL
              value: http://analytics-service:8084
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests: { cpu: 100m, memory: 384Mi }
            limits: { cpu: 500m, memory: 768Mi }
